package mozc_runtime

import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.Test
import kotlin.test.assertTrue

class MozcRequiredModuleCoverageTest {
    private val repoRoot: Path = Path.of(System.getProperty("user.dir"))

    @Test
    fun requiredMozcDataAndRuntimeSourceFilesExist() {
        val requiredFiles = listOf(
            "src/main/kotlin/mozc_data/MozcDataGenerationMain.kt",
            "src/main/kotlin/mozc_data/MozcOfficialDataBuilder.kt",
            "src/main/kotlin/mozc_data/MozcDataSetReader.kt",
            "src/main/kotlin/mozc_data/MozcDataSetWriter.kt",
            "src/main/kotlin/mozc_data/MozcDataManager.kt",
            "src/main/kotlin/mozc_data/MozcDataSection.kt",
            "src/main/kotlin/mozc_data/MozcDataManifest.kt",
            "src/main/kotlin/mozc_data/MozcDataManifestWriter.kt",
            "src/main/kotlin/mozc_data/MozcDataVerifier.kt",
            "src/main/kotlin/mozc_data/MozcDataVersion.kt",
            "src/main/kotlin/mozc_data/DataSetMetadataParser.kt",
            "src/main/kotlin/mozc_data/DataSetMetadataWriter.kt",
            "src/main/kotlin/mozc_runtime/data/SerializedStringArray.kt",
            "src/main/kotlin/mozc_runtime/data/SerializedDictionary.kt",
            "src/main/kotlin/mozc_runtime/dictionary/file/DictionaryFile.kt",
            "src/main/kotlin/mozc_runtime/dictionary/file/DictionaryFileCodec.kt",
            "src/main/kotlin/mozc_runtime/dictionary/file/DictionaryFileSection.kt",
            "src/main/kotlin/mozc_runtime/dictionary/system/SystemDictionary.kt",
            "src/main/kotlin/mozc_runtime/dictionary/system/SystemDictionaryCodec.kt",
            "src/main/kotlin/mozc_runtime/dictionary/system/ValueDictionary.kt",
            "src/main/kotlin/mozc_runtime/dictionary/system/KeyExpansionTable.kt",
            "src/main/kotlin/mozc_runtime/dictionary/system/TokenDecodeIterator.kt",
            "src/main/kotlin/mozc_runtime/dictionary/system/WordsInfo.kt",
            "src/main/kotlin/mozc_runtime/storage/louds/LoudsTrie.kt",
            "src/main/kotlin/mozc_runtime/storage/louds/BitStream.kt",
            "src/main/kotlin/mozc_runtime/storage/louds/BitVectorBasedArray.kt",
            "src/main/kotlin/mozc_runtime/storage/louds/SimpleSuccinctBitVectorIndex.kt",
            "src/main/kotlin/mozc_runtime/dictionary/Token.kt",
            "src/main/kotlin/mozc_runtime/dictionary/DictionaryInterface.kt",
            "src/main/kotlin/mozc_runtime/dictionary/DictionaryImpl.kt",
            "src/main/kotlin/mozc_runtime/dictionary/PosMatcher.kt",
            "src/main/kotlin/mozc_runtime/dictionary/PosGroup.kt",
            "src/main/kotlin/mozc_runtime/dictionary/UserPos.kt",
            "src/main/kotlin/mozc_runtime/dictionary/UserDictionary.kt",
            "src/main/kotlin/mozc_runtime/dictionary/SuffixDictionary.kt",
            "src/main/kotlin/mozc_runtime/converter/Connector.kt",
            "src/main/kotlin/mozc_runtime/converter/Segmenter.kt",
            "src/main/kotlin/mozc_runtime/converter/Attribute.kt",
            "src/main/kotlin/mozc_runtime/converter/Candidate.kt",
            "src/main/kotlin/mozc_runtime/converter/InnerSegment.kt",
            "src/main/kotlin/mozc_runtime/converter/Node.kt",
            "src/main/kotlin/mozc_runtime/converter/NodeAllocator.kt",
            "src/main/kotlin/mozc_runtime/converter/NodeListBuilder.kt",
            "src/main/kotlin/mozc_runtime/converter/Lattice.kt",
            "src/main/kotlin/mozc_runtime/converter/Segment.kt",
            "src/main/kotlin/mozc_runtime/converter/Segments.kt",
            "src/main/kotlin/mozc_runtime/converter/KeyCorrector.kt",
            "src/main/kotlin/mozc_runtime/converter/ImmutableConverter.kt",
            "src/main/kotlin/mozc_runtime/converter/NBestGenerator.kt",
            "src/main/kotlin/mozc_runtime/converter/CandidateFilter.kt",
            "src/main/kotlin/mozc_runtime/converter/HistoryReconstructor.kt",
            "src/main/kotlin/mozc_runtime/converter/ReverseConverter.kt",
            "src/main/kotlin/mozc_runtime/converter/Converter.kt",
            "src/main/kotlin/mozc_runtime/prediction/Predictor.kt",
            "src/main/kotlin/mozc_runtime/prediction/DictionaryPredictor.kt",
            "src/main/kotlin/mozc_runtime/prediction/DictionaryPredictionAggregator.kt",
            "src/main/kotlin/mozc_runtime/prediction/UserHistoryPredictor.kt",
            "src/main/kotlin/mozc_runtime/prediction/UserHistoryStorage.kt",
            "src/main/kotlin/mozc_runtime/prediction/RealtimeDecoder.kt",
            "src/main/kotlin/mozc_runtime/prediction/Result.kt",
            "src/main/kotlin/mozc_runtime/prediction/ResultFilter.kt",
            "src/main/kotlin/mozc_runtime/prediction/SuggestionFilter.kt",
            "src/main/kotlin/mozc_runtime/prediction/ZeroQueryDict.kt",
            "src/main/kotlin/mozc_runtime/prediction/NumberDecoder.kt",
            "src/main/kotlin/mozc_runtime/prediction/SingleKanjiDecoder.kt",
            "src/main/kotlin/mozc_runtime/rewriter/Rewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/MergerRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/FocusCandidateRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/LanguageAwareRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/TransliterationRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/EnglishVariantsRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/NumberRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/CollocationRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/SingleKanjiRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/IvsVariantsRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/EmoticonRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/EmojiRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/CalculatorRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/SymbolRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/UnicodeRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/VariantsRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/ZipcodeRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/DiceRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/SmallLetterRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/UserBoundaryHistoryRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/UserSegmentHistoryRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/DateRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/FortuneRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/UsageRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/VersionRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/CorrectionRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/T13nPromotionRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/EnvironmentalFilterRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/RemoveRedundantCandidateRewriter.kt",
            "src/main/kotlin/mozc_runtime/rewriter/A11yDescriptionRewriter.kt",
            "src/main/kotlin/mozc_runtime/engine/MozcModules.kt",
            "src/main/kotlin/mozc_runtime/engine/MozcKotlinEngine.kt",
            "src/main/kotlin/mozc_runtime/engine/MozcKotlinEngineConverter.kt",
            "src/main/kotlin/mozc_runtime/engine/MozcConversionRequest.kt",
            "src/main/kotlin/mozc_runtime/engine/MozcEngineCandidate.kt",
            "src/main/kotlin/mozc_runtime/engine/MozcEngineResult.kt",
        )
        val missing = requiredFiles.filterNot { Files.isRegularFile(repoRoot.resolve(it)) }
        assertTrue(missing.isEmpty(), "Missing required Mozc Kotlin runtime files:\n${missing.joinToString(separator = "\n")}")
    }
}
