package com.kazumaproject.english

import com.kazumaproject.dictionary.models.Dictionary
import java.io.BufferedReader
import java.io.InputStream
import java.io.InputStreamReader
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path

/**
 * Reads the five-column Mozc source generated by JapaneseCorpus.
 *
 * The source is intentionally kept as a separate dictionary from the large
 * Mozc dictionaries.  JapaneseCorpus already emits the exact format used by
 * [Dictionary], so no translation or surface rewriting is performed here.
 */
class EnglishDictionaryBuilder {

    fun parse(path: Path, expectedContextId: Int? = null): List<Dictionary> =
        Files.newBufferedReader(path, StandardCharsets.UTF_8).use { reader ->
            parse(reader, path.toString(), expectedContextId)
        }

    fun parseResource(
        resourcePath: String,
        required: Boolean = true,
        expectedContextId: Int? = null,
    ): List<Dictionary> {
        val stream = EnglishDictionaryBuilder::class.java.getResourceAsStream(resourcePath)
        if (stream == null) {
            require(!required) {
                "English dictionary resource was not found: resource path=$resourcePath. " +
                        "Download JapaneseCorpus's mozc-english-unigram asset and expand it to " +
                        "src/main/resources/english-dictionary.txt."
            }
            return emptyList()
        }
        return stream.use { parse(it, resourcePath, expectedContextId) }
    }

    fun parse(
        input: InputStream,
        sourceName: String,
        expectedContextId: Int? = null,
    ): List<Dictionary> =
        InputStreamReader(input, StandardCharsets.UTF_8).buffered().use { reader ->
            parse(reader, sourceName, expectedContextId)
        }

    private fun parse(
        reader: BufferedReader,
        sourceName: String,
        expectedContextId: Int?,
    ): List<Dictionary> {
        val result = ArrayList<Dictionary>()
        reader.forEachLineIndexed { lineNumber, rawLine ->
            if (rawLine.isBlank() || rawLine.trimStart().startsWith("#")) return@forEachLineIndexed

            val fields = rawLine.split('\t', limit = 5)
            require(fields.size == 5) {
                invalidLine(sourceName, lineNumber, rawLine, "expected exactly five tab-separated columns")
            }

            val yomi = fields[0]
            val leftId = fields[1].toIntOrNull()
            val rightId = fields[2].toIntOrNull()
            val cost = fields[3].toIntOrNull()
            val tango = fields[4]

            require(yomi.isNotEmpty()) {
                invalidLine(sourceName, lineNumber, rawLine, "reading must not be empty")
            }
            require(tango.isNotEmpty()) {
                invalidLine(sourceName, lineNumber, rawLine, "English surface must not be empty")
            }
            require(leftId != null && rightId != null) {
                invalidLine(sourceName, lineNumber, rawLine, "left_id and right_id must be integers")
            }
            require(cost != null && cost in 1..Short.MAX_VALUE) {
                invalidLine(sourceName, lineNumber, rawLine, "cost must be in the positive Short range")
            }
            require(leftId in Short.MIN_VALUE..Short.MAX_VALUE && rightId in Short.MIN_VALUE..Short.MAX_VALUE) {
                invalidLine(sourceName, lineNumber, rawLine, "left_id and right_id must fit in Short")
            }
            require(yomi.toByteArray(StandardCharsets.UTF_8).size <= MAX_FIELD_BYTES) {
                invalidLine(sourceName, lineNumber, rawLine, "reading exceeds the Mozc field size limit")
            }
            require(tango.toByteArray(StandardCharsets.UTF_8).size <= MAX_FIELD_BYTES) {
                invalidLine(sourceName, lineNumber, rawLine, "English surface exceeds the Mozc field size limit")
            }
            require(tango.none { it.isISOControl() || it == '\t' }) {
                invalidLine(sourceName, lineNumber, rawLine, "English surface contains a control character")
            }
            if (expectedContextId != null) {
                require(leftId == expectedContextId && rightId == expectedContextId) {
                    invalidLine(
                        sourceName,
                        lineNumber,
                        rawLine,
                        "dictionary context IDs must match expected generic-noun ID=$expectedContextId",
                    )
                }
            }

            result += Dictionary(
                yomi = yomi,
                leftId = leftId.toShort(),
                rightId = rightId.toShort(),
                cost = cost.toShort(),
                tango = tango,
            )
        }
        return result
    }

    private fun invalidLine(sourceName: String, lineNumber: Int, rawLine: String, reason: String): String =
        "Invalid English dictionary source: source=$sourceName, line=$lineNumber, reason=$reason, raw='$rawLine'"

    private companion object {
        const val MAX_FIELD_BYTES = 256
    }
}

private fun BufferedReader.forEachLineIndexed(action: (lineNumber: Int, line: String) -> Unit) {
    var lineNumber = 0
    forEachLine { line ->
        lineNumber += 1
        action(lineNumber, line)
    }
}
