name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger only when a tag starting with "v" is pushed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 for Kotlin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Run the Kotlin application
      - name: Run main.kt
        run: ./gradlew run

      # Upload artifacts to GitHub Actions
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./src/main/resources/connectionId.dat
            ./src/main/resources/pos_table.dat
            ./src/main/resources/yomi_singleKanji.dat
            ./src/main/resources/tango_singleKanji.dat
            ./src/main/resources/token_singleKanji.dat
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat
            ./src/main/resources/yomi_emoji.dat
            ./src/main/resources/tango_emoji.dat
            ./src/main/resources/token_emoji.dat
            ./src/main/resources/yomi_emoticon.dat
            ./src/main/resources/tango_emoticon.dat
            ./src/main/resources/token_emoticon.dat
            ./src/main/resources/yomi_symbol.dat
            ./src/main/resources/tango_symbol.dat
            ./src/main/resources/token_symbol.dat
            ./src/main/resources/yomi_reading_correction.dat
            ./src/main/resources/tango_reading_correction.dat
            ./src/main/resources/token_reading_correction.dat
            ./src/main/resources/yomi_kotowaza.dat
            ./src/main/resources/tango_kotowaza.dat
            ./src/main/resources/token_kotowaza.dat
            ./src/main/resources/yomi_person_names.dat
            ./src/main/resources/tango_person_names.dat
            ./src/main/resources/token_person_names.dat
            ./src/main/resources/yomi_places.dat
            ./src/main/resources/tango_places.dat
            ./src/main/resources/token_places.dat
            ./src/main/resources/yomi_wiki.dat
            ./src/main/resources/tango_wiki.dat
            ./src/main/resources/token_wiki.dat

      # Create a GitHub Release and upload artifacts
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          artifacts: |
            ./src/main/resources/connectionId.dat
            ./src/main/resources/pos_table.dat
            ./src/main/resources/yomi_singleKanji.dat
            ./src/main/resources/tango_singleKanji.dat
            ./src/main/resources/token_singleKanji.dat
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat
            ./src/main/resources/yomi_emoji.dat
            ./src/main/resources/tango_emoji.dat
            ./src/main/resources/token_emoji.dat
            ./src/main/resources/yomi_emoticon.dat
            ./src/main/resources/tango_emoticon.dat
            ./src/main/resources/token_emoticon.dat
            ./src/main/resources/yomi_symbol.dat
            ./src/main/resources/tango_symbol.dat
            ./src/main/resources/token_symbol.dat
            ./src/main/resources/yomi_reading_correction.dat
            ./src/main/resources/tango_reading_correction.dat
            ./src/main/resources/token_reading_correction.dat
            ./src/main/resources/yomi_kotowaza.dat
            ./src/main/resources/tango_kotowaza.dat
            ./src/main/resources/token_kotowaza.dat
            ./src/main/resources/yomi_person_names.dat
            ./src/main/resources/tango_person_names.dat
            ./src/main/resources/token_person_names.dat
            ./src/main/resources/yomi_places.dat
            ./src/main/resources/tango_places.dat
            ./src/main/resources/token_places.dat
            ./src/main/resources/yomi_wiki.dat
            ./src/main/resources/tango_wiki.dat
            ./src/main/resources/token_wiki.dat
