name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Also run when a version tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 for Kotlin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Download dictionary and required text files
      - name: Download required text files
        run: |
          mkdir -p ./src/main/resources
          # Download dictionary files
          for i in $(seq -w 00 09); do
            wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/dictionary${i}.txt -O ./src/main/resources/dictionary${i}.txt
          done
          # Download additional files from dictionary_oss
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/connection_single_column.txt -O ./src/main/resources/connection_single_column.txt
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/suffix.txt -O ./src/main/resources/suffix.txt
          # Download single_kanji.tsv from the single_kanji directory
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/single_kanji/single_kanji.tsv -O ./src/main/resources/single_kanji.tsv

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Run the Kotlin application
      - name: Run main.kt
        run: ./gradlew run

      # Upload binary files as artifacts
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yomi-tango-token
          path: |
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Create GitHub Release and upload artifacts
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat