name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger only when a tag starting with "v" is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download required text files
        run: |
          mkdir -p ./src/main/resources
          # Download dictionary files
          for i in $(seq -w 00 09); do
            wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/dictionary${i}.txt -O ./src/main/resources/dictionary${i}.txt
          done
          # Download additional files from dictionary_oss
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/connection_single_column.txt -O ./src/main/resources/connection_single_column.txt
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/suffix.txt -O ./src/main/resources/suffix.txt
          # Download single_kanji.tsv from the single_kanji directory
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/single_kanji/single_kanji.tsv -O ./src/main/resources/single_kanji.tsv

      - name: Build with Gradle
        run: ./gradlew build

  run-main:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run main.kt
        run: ./gradlew run

      - name: Upload main output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-output
          path: ./src/main/resources/

  run-mozcut:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build MozcUT Dictionaries
        run: ./gradlew runMozcUT

      - name: Upload MozcUT output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mozcUT-output
          path: ./src/main/resources/

  upload:
    runs-on: ubuntu-latest
    needs: [ run-main, run-mozcut ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./src/main/resources/

      - name: Upload artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          artifacts: ./src/main/resources/*
