# GitHub Actions Workflow: Build and Release All Mozc Dictionaries

name: Build and Release Mozc Dictionary

on:
  push:
    tags:
      - 'v*'  # Trigger only when a tag starting with "v" is pushed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 for Kotlin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Download base dictionary files
      - name: Download base dictionary files
        run: |
          mkdir -p ./src/main/resources
          for i in $(seq -w 00 09); do
            wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/dictionary${i}.txt -O ./src/main/resources/dictionary${i}.txt
          done
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/connection_single_column.txt -O ./src/main/resources/connection_single_column.txt
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/suffix.txt -O ./src/main/resources/suffix.txt
          wget https://raw.githubusercontent.com/google/mozc/master/src/data/single_kanji/single_kanji.tsv -O ./src/main/resources/single_kanji.tsv

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # --- Run all dictionary creation tasks in parallel ---
      # 各タスクをバックグラウンドで並列実行し、すべての完了を待ちます。
      - name: Run all dictionary creation tasks in parallel
        run: |
          ./gradlew run &
          ./gradlew runMozcUT &
          ./gradlew runMozcUTWiki &
          ./gradlew runMozcUTNeologd &
          ./gradlew runMozcUTWikiNeologdCommon &
          wait

      # --- Create a single release with all generated artifacts ---
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          artifacts: |
            # --- Artifacts from main.kt ---
            ./src/main/resources/connectionId.dat
            ./src/main/resources/pos_table.dat
            ./src/main/resources/yomi_singleKanji.dat
            ./src/main/resources/tango_singleKanji.dat
            ./src/main/resources/token_singleKanji.dat
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat
            ./src/main/resources/yomi_emoji.dat
            ./src/main/resources/tango_emoji.dat
            ./src/main/resources/token_emoji.dat
            ./src/main/resources/yomi_emoticon.dat
            ./src/main/resources/tango_emoticon.dat
            ./src/main/resources/token_emoticon.dat
            ./src/main/resources/yomi_symbol.dat
            ./src/main/resources/tango_symbol.dat
            ./src/main/resources/token_symbol.dat
            ./src/main/resources/yomi_reading_correction.dat
            ./src/main/resources/tango_reading_correction.dat
            ./src/main/resources/token_reading_correction.dat
            ./src/main/resources/yomi_kotowaza.dat
            ./src/main/resources/tango_kotowaza.dat
            ./src/main/resources/token_kotowaza.dat
            
            # --- Artifacts from MozcUT.kt ---
            ./src/main/resources/yomi_person_names.dat
            ./src/main/resources/tango_person_names.dat
            ./src/main/resources/token_person_names.dat
            ./src/main/resources/yomi_places.dat
            ./src/main/resources/tango_places.dat
            ./src/main/resources/token_places.dat
            
            # --- Artifacts from MozcUTWiki.kt ---
            ./src/main/resources/yomi_wiki.dat
            ./src/main/resources/tango_wiki.dat
            ./src/main/resources/token_wiki.dat

            # --- Artifacts from MozcUTNeologd.kt ---
            ./src/main/resources/yomi_neologd.dat
            ./src/main/resources/tango_neologd.dat
            ./src/main/resources/token_neologd.dat
            
            # --- Artifacts from MozcUTWikiNeologdCommon.kt ---
            ./src/main/resources/yomi_web.dat
            ./src/main/resources/tango_web.dat
            ./src/main/resources/token_web.dat
          replacesArtifacts: false
