name: Build and Release Mozc Dictionary

on:
  push:
    tags:
      - 'v*'  # Trigger only when a tag starting with "v" is pushed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 for Kotlin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Download base dictionary files (pinned to specific Mozc commit)
      - name: Download base dictionary files
        run: |
          mkdir -p ./src/main/resources
          for i in $(seq -w 00 09); do
            wget https://raw.githubusercontent.com/google/mozc/5e0ca019f20bf91490a5eda0a4a5f00fc35815c0/src/data/dictionary_oss/dictionary${i}.txt -O ./src/main/resources/dictionary${i}.txt
          done
          wget https://raw.githubusercontent.com/google/mozc/5e0ca019f20bf91490a5eda0a4a5f00fc35815c0/src/data/dictionary_oss/connection_single_column.txt -O ./src/main/resources/connection_single_column.txt
          wget https://raw.githubusercontent.com/google/mozc/5e0ca019f20bf91490a5eda0a4a5f00fc35815c0/src/data/dictionary_oss/suffix.txt -O ./src/main/resources/suffix.txt
          wget https://raw.githubusercontent.com/google/mozc/5e0ca019f20bf91490a5eda0a4a5f00fc35815c0/src/data/single_kanji/single_kanji.tsv -O ./src/main/resources/single_kanji.tsv

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # --- Run all dictionary creation tasks in parallel ---
      # 各タスクをバックグラウンドで並列実行し、すべての完了を待ちます。
      - name: Run all dictionary creation tasks in parallel
        run: |
          ./gradlew run &
          ./gradlew runMozcUT &
          ./gradlew runMozcUTWiki &
          ./gradlew runMozcUTNeologd &
          ./gradlew runMozcUTWikiNeologdCommon &
          wait

      # --- (新規) リリース用に成果物を整理し、zip圧縮する ---
      - name: Organize and zip artifacts for release
        run: |
          # zipファイルと、その中に入れるファイル用のディレクトリを作成
          mkdir -p release_zips
          mkdir -p artifacts_temp/main artifacts_temp/mozc_ut artifacts_temp/mozc_ut_wiki artifacts_temp/mozc_ut_neologd artifacts_temp/web

          # main.kt由来のファイルを移動
          mv ./src/main/resources/{yomi_singleKanji,tango_singleKanji,token_singleKanji}.dat artifacts_temp/main/
          mv ./src/main/resources/{yomi,tango,token}.dat artifacts_temp/main/
          mv ./src/main/resources/{yomi,tango,token}_emoji.dat artifacts_temp/main/
          mv ./src/main/resources/{yomi,tango,token}_emoticon.dat artifacts_temp/main/
          mv ./src/main/resources/{yomi,tango,token}_symbol.dat artifacts_temp/main/
          mv ./src/main/resources/{yomi,tango,token}_reading_correction.dat artifacts_temp/main/
          mv ./src/main/resources/{yomi,tango,token}_kotowaza.dat artifacts_temp/main/

          # MozcUT.kt由来のファイルを移動
          mv ./src/main/resources/*_{person_names,places}.dat artifacts_temp/mozc_ut/

          # MozcUTWiki.kt由来のファイルを移動
          mv ./src/main/resources/*_wiki.dat artifacts_temp/mozc_ut_wiki/

          # MozcUTNeologd.kt由来のファイルを移動
          mv ./src/main/resources/*_neologd.dat artifacts_temp/mozc_ut_neologd/
          
          # MozcUTWikiNeologdCommon.kt由来のファイルを移動
          mv ./src/main/resources/*_web.dat artifacts_temp/web/

          # 各ディレクトリをzip圧縮
          (cd artifacts_temp/main && zip -r ../../release_zips/main_dictionaries.zip .)
          (cd artifacts_temp/mozc_ut && zip -r ../../release_zips/mozc_ut_dictionaries.zip .)
          (cd artifacts_temp/mozc_ut_wiki && zip -r ../../release_zips/wiki_dictionary.zip .)
          (cd artifacts_temp/mozc_ut_neologd && zip -r ../../release_zips/neologd_dictionary.zip .)
          (cd artifacts_temp/web && zip -r ../../release_zips/web_dictionary.zip .)

      # --- Create a single release with all generated artifacts ---
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          # ルートに配置するファイルと、各辞書をまとめたzipファイルを指定
          artifacts: |
            ./src/main/resources/connectionId.dat
            ./src/main/resources/pos_table.dat
            ./release_zips/main_dictionaries.zip
            ./release_zips/mozc_ut_dictionaries.zip
            ./release_zips/wiki_dictionary.zip
            ./release_zips/neologd_dictionary.zip
            ./release_zips/web_dictionary.zip
          replacesArtifacts: false
