name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Runs only when a version tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 for Kotlin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the project with Gradle or Maven
      - name: Build with Gradle
        run: ./gradlew build # Adjust this to your actual build command

      # Run the Kotlin application
      - name: Run main.kt
        run: ./gradlew run # Adjust this if necessary

      # Upload binary files as artifacts
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yomi-tango-token
          path: |
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a release and upload artifacts
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            ./src/main/resources/yomi.dat
            ./src/main/resources/tango.dat
            ./src/main/resources/token.dat